// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psxexceumklqhoguhpxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzeGV4Y2V1bWtscWhvZ3VocHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDM4MjUsImV4cCI6MjA3MDQ3OTgyNX0.o65JrrcgtGhXkMzTpc9R_U-9gk01om_jBMzT8aVndXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});